<?php

declare(strict_types=1);

namespace Passway\Services;

use RobThree\Auth\Providers\Qr\BaconQrCodeProvider;
use Passway\Exceptions\DecryptionException;
use RobThree\Auth\TwoFactorAuth;
use RobThree\Auth\TwoFactorAuthException;

/**
 * TOTP (Time-based One-Time Password) service based on robthree/twofactorauth.
 *
 * Storage secret:
 *   - raw Base32 secret is generated by the library
 *   - is encrypted through EncryptionService (XChaCha20-Poly1305)
 *   - in DB: users.totp_secret (encrypted_value), users.totp_nonce
 *
 * NEVER stores plaintext secret in the DB or logs.
 */
final class TotpService
{
    private readonly TwoFactorAuth $tfa;

    public function __construct(
        private readonly EncryptionService $encryptionService,
    ) {
        // Issuer - displayed in the TOTP app (Google Authenticator, Authy, etc.)
        $issuer = (string) ($_ENV['APP_NAME'] ?? 'Passway');
        $this->tfa = new TwoFactorAuth(
            issuer: $issuer,
            qrcodeprovider: new BaconQrCodeProvider(format: 'svg'),
        );
    }

    // ------------------------------------------------------------------ //
    //  Secret generation                                                  //
    // ------------------------------------------------------------------ //

    /**
     * Generate a new TOTP secret and encrypt it.
     *
     * Returns an array for writing to users:
     *   ['totp_secret' => string, 'totp_nonce' => string]
     *
     * @return array{totp_secret: string, totp_nonce: string, raw_secret: string}
     * @throws TwoFactorAuthException
     */
    public function generateSecret(): array
    {
        // 160 bits (32 Base32-characters) - TOTP RFC recommends >= 128 bits
        $rawSecret = $this->tfa->createSecret(160);

        $encrypted = $this->encryptionService->encrypt($rawSecret);

        return [
            'totp_secret' => $encrypted->value,
            'totp_nonce'  => $encrypted->nonce,
            'raw_secret'  => $rawSecret, // возвращаем для QR-кода, НЕ хранить
        ];
    }

    // ------------------------------------------------------------------ //
    //  QR code                                                             //
    // ------------------------------------------------------------------ //

    /**
     * Return an otpauth:// URI for client-side QR code generation.
     *
     * @param string $email       User email (label in URI)
     * @param string $rawSecret   Plaintext Base32 secret (from generateSecret())
     */
    public function getQrCodeUri(string $email, string $rawSecret): string
    {
        // Format: otpauth://totp/{issuer}:{email}?secret={secret}&issuer={issuer}
        return $this->tfa->getQRText($email, $rawSecret);
    }

    /**
     * Return an embedded QR-code SVG image for display in the web interface.
     */
    public function getQrCodeImageDataUri(string $email, string $rawSecret, int $size = 220): string
    {
        return $this->tfa->getQRCodeImageAsDataUri($email, $rawSecret, $size);
    }

    /**
     * Decrypt the secret and return the QR URI.
     * Used when QR needs to be shown again after registration.
     *
     * @throws DecryptionException
     */
    public function getQrCodeUriFromDb(string $email, string $encryptedSecret, string $nonce): string
    {
        $rawSecret = $this->encryptionService->decrypt($encryptedSecret, $nonce);
        return $this->getQrCodeUri($email, $rawSecret);
    }

    // ------------------------------------------------------------------ //
    //  Code verification                                                   //
    // ------------------------------------------------------------------ //

    /**
     * Verify the TOTP code against the encrypted secret from the DB.
     *
     * @param string $encryptedSecret users.totp_secret
     * @param string $nonce           users.totp_nonce
     * @param string $code            User-entered 6-digit code
     * @param int    $discrepancy     Allowed period discrepancy (default: 1 = ±30 sec)
     *
     * @throws DecryptionException if the secret cannot be decrypted
     */
    public function verifyCode(
        string $encryptedSecret,
        string $nonce,
        string $code,
        int    $discrepancy = 1,
    ): bool {
        // Code sanitization - digits only
        $code = \preg_replace('/\D/', '', $code) ?? '';
        if (\strlen($code) !== 6) {
            return false;
        }

        $rawSecret = $this->encryptionService->decrypt($encryptedSecret, $nonce);

        try {
            return $this->tfa->verifyCode($rawSecret, $code, $discrepancy);
        } catch (TwoFactorAuthException) {
            return false;
        } finally {
            // Wipe the decrypted secret from memory
            \sodium_memzero($rawSecret);
        }
    }

    /**
     * Verify a code against the raw secret (used when first enabling 2FA).
     */
    public function verifyCodeRaw(string $rawSecret, string $code, int $discrepancy = 1): bool
    {
        $code = \preg_replace('/\D/', '', $code) ?? '';
        if (\strlen($code) !== 6) {
            return false;
        }

        try {
            return $this->tfa->verifyCode($rawSecret, $code, $discrepancy);
        } catch (TwoFactorAuthException) {
            return false;
        }
    }
}
